# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
        exclude: "^.helm/.*$"
        args:
          - --unsafe

      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff
        name: Check code style with Ruff
        language: system
        entry: uv run ruff check --fix
        pass_filenames: false
        types:
          - python

      - id: mypy
        name: Check static types with mypy
        language: system
        entry: uv run mypy .
        pass_filenames: false
        types_or:
          - python
          - pyi
