"""made name and age fields optional in User

Revision ID: 8069d4d50662
Revises: 348b64e87aac
Create Date: 2025-05-04 14:17:56.232541+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8069d4d50662"
down_revision: Union[str, None] = "348b64e87aac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=20), nullable=True)
    op.alter_column("users", "age", existing_type=sa.SMALLINT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "age", existing_type=sa.SMALLINT(), nullable=False)
    op.alter_column("users", "name", existing_type=sa.VARCHAR(length=20), nullable=False)
    # ### end Alembic commands ###
