"""add new field in User

Revision ID: 348b64e87aac
Revises: ad1f3eced5d4
Create Date: 2025-04-19 09:26:46.728899+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "348b64e87aac"
down_revision: Union[str, None] = "ad1f3eced5d4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("wallet_address", sa.String(length=48), nullable=True))
    op.create_unique_constraint(None, "users", ["wallet_address"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "wallet_address")
    # ### end Alembic commands ###
